architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/molten_metals.accesswidener")
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modImplementation "dev.architectury:architectury:${rootProject.architectury_version}"
    modImplementation "maven.modrinth:moonlight:${rootProject.moonlight_version}"
}

processResources {
    exclude("resourcepacks/")
}

sourceSets.main {
    resources {
        srcDir("src/generated/resources")
        exclude("src/generated/resources/.cache")
    }
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
        }
    }
    repositories {
    }
}

repositories {
    maven { url "https://maven.terraformersmc.com/releases" }
}
